In [2]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [5]:
arr1=np.random.randint(1,high=21,size=(5,5))
print(arr1)

[[ 4 19 20  6 12]
 [14  7  1 17 20]
 [11 11 17 20  3]
 [20 15 16  7  4]
 [ 5  7  9 12 12]]


In [6]:
arr1[:,2]=1
print(arr1)

[[ 4 19  1  6 12]
 [14  7  1 17 20]
 [11 11  1 20  3]
 [20 15  1  7  4]
 [ 5  7  1 12 12]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [7]:
arr2=np.random.randint(1,17,size=(4,4))
print(arr2)

[[ 9 12  4 11]
 [ 3 14 13 11]
 [ 5 10  3 16]
 [14 10  4  9]]


In [8]:
np.fill_diagonal(arr2,0)
print(arr2)

[[ 0 12  4 11]
 [ 3  0 13 11]
 [ 5 10  0 16]
 [14 10  4  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [9]:
arr3=np.random.randint(1,37,size=(6,6))
print(arr3)

[[26  4 34 16 32 14]
 [20 34 33 10 31 35]
 [ 3 10  7  5 32 22]
 [26 13  1 33 17 21]
 [ 2  8 28 26 29 28]
 [ 5  1 35 12 17  1]]


In [10]:
sub_arr3=arr3[2:5,1:4]
print(sub_arr3)

[[10  7  5]
 [13  1 33]
 [ 8 28 26]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [11]:
arr3=np.random.randint(1,11,size=(5,5))
print(arr3)

[[ 3  8  4  2  2]
 [ 2  9  3  1  5]
 [ 1  7 10  6  5]
 [ 6  8  1  5  2]
 [ 2  3  8  4  7]]


In [12]:
print(arr3[0])
print(arr3[:,-1])
print(arr3[-1])
print(arr3[:,0])

[3 8 4 2 2]
[2 5 5 2 7]
[2 3 8 4 7]
[3 2 1 6 2]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [13]:
arr1=np.random.randint(1,6,size=(3,4))
arr2=np.random.randint(1,6,size=(3,4))

print("First array:\n",arr1)
print("Second array:\n",arr2)

print("Addition:\n",arr1+arr2)
print("Subtraction:\n",arr1-arr2)
print("Multiplication:\n",arr1*arr2)
print("Divison:\n",arr1/arr2)

First array:
 [[1 2 4 2]
 [2 3 3 2]
 [4 4 5 1]]
Second array:
 [[2 3 5 1]
 [3 2 3 1]
 [1 1 2 5]]
Addition:
 [[3 5 9 3]
 [5 5 6 3]
 [5 5 7 6]]
Subtraction:
 [[-1 -1 -1  1]
 [-1  1  0  1]
 [ 3  3  3 -4]]
Multiplication:
 [[ 2  6 20  2]
 [ 6  6  9  2]
 [ 4  4 10  5]]
Divison:
 [[0.5        0.66666667 0.8        2.        ]
 [0.66666667 1.5        1.         2.        ]
 [4.         4.         2.5        0.2       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [14]:
arr1=np.random.randint(1,17,size=(4,4))
arr1

array([[ 8, 11, 12, 14],
       [14,  4,  8,  6],
       [ 5, 15, 12, 16],
       [ 1, 15,  8,  2]], dtype=int32)

In [15]:
row_sums=np.sum(arr1,axis=1)
print (row_sums)

[45 32 48 26]


In [16]:
col_sums=np.sum(arr1,axis=0)
print(col_sums)

[28 45 40 38]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [17]:
arr1=np.random.randint(1,11,size=(5,5))
arr1

array([[ 4,  7, 10,  8,  3],
       [ 8,  7,  2,  7,  4],
       [ 1, 10,  5,  9,  9],
       [10,  9,  4,  5,  5],
       [ 4,  5,  8,  4, 10]], dtype=int32)

In [18]:
print("Mean :",np.mean(arr1))
print("Median :",np.median(arr1))
print("Standard Deviation :",np.std(arr1))
print("Variance :",np.var(arr1))

Mean : 6.32
Median : 7.0
Standard Deviation : 2.664132128855474
Variance : 7.0976


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [19]:
arr1=np.random.randint(1,10,size=(3,3))
print(arr1)

[[7 7 4]
 [9 4 6]
 [3 2 2]]


In [ ]:
mean=np.mean(arr1)
standard_deviation=np.std(arr1)
print("Mean :",mean)
print("Standard Deviation :",standard_deviation)
normalised_array=(arr1-mean)/standard_deviation
print("Normalised Array:\n",normalised_array)
print("New Mean :",np.mean(normalised_array))
print("New Standard Deviation:",np.std(normalised_array))

Mean : 4.0
Standard Deviation : 2.160246899469287
Normalised Array:
 [[ 0.46291005  0.46291005  0.9258201 ]
 [-0.9258201  -0.46291005 -1.38873015]
 [ 1.38873015  0.9258201  -1.38873015]]
New Mean : -2.4671622769447922e-17
New Standard Deviation: 1.0


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcastin

In [30]:
arr1=np.random.randint(1,10,size=(3,3))
print(arr1)

[[4 8 1]
 [9 1 6]
 [2 3 3]]


In [31]:
arr2=[1,1,1]
arr1=arr1+arr2
print(arr1)

[[ 5  9  2]
 [10  2  7]
 [ 3  4  4]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [57]:
arr1=np.random.randint(1,10,size=(4,4))
print(arr1)

[[2 9 5 3]
 [9 6 4 8]
 [5 5 3 4]
 [6 7 4 6]]


In [58]:
arr2=np.ones(4)
arr1=arr1-arr2
print(arr1)

[[1. 8. 4. 2.]
 [8. 5. 3. 7.]
 [4. 4. 2. 3.]
 [5. 6. 3. 5.]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [9]:
arr1=np.random.randint(1,10,size=(3,3))
print(arr1)

[[9 9 3]
 [5 6 2]
 [7 5 9]]


In [10]:
print("deteminant:",np.linalg.det(arr1))
print("Inverse:\n",np.linalg.inv(arr1))
print("Eigen Values:\n",np.linalg.eigvals(arr1))

deteminant: 65.99999999999997
Inverse:
 [[ 6.66666667e-01 -1.00000000e+00 -8.63506797e-17]
 [-4.69696970e-01  9.09090909e-01 -4.54545455e-02]
 [-2.57575758e-01  2.72727273e-01  1.36363636e-01]]
Eigen Values:
 [17.88975904  0.67930491  5.43093605]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [12]:
arr1=np.random.randint(1,10,size=(2,3))
arr2=np.random.randint(1,10,size=(3,2))
print("First array:\n",arr1)
print("Second array:\n",arr2)

First array:
 [[9 7 2]
 [6 1 3]]
Second array:
 [[5 7]
 [7 2]
 [1 9]]


In [13]:
print(np.matmul(arr1,arr2))

[[96 95]
 [40 71]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
arr1=np.random.randint(1,10,size=(3,3))
print(arr1)

[[9 1 5]
 [8 3 3]
 [9 9 1]]


In [ ]:
arr1=arr1.reshape(1,9)
print(arr1)

[[9 1 5 8 3 3 9 9 1]]


In [18]:
arr1=arr1.reshape(9,1)
print(arr1)

[[9]
 [1]
 [5]
 [8]
 [3]
 [3]
 [9]
 [9]
 [1]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [19]:
arr1=np.random.randint(1,10,size=(5,5))
print(arr1)

[[5 2 6 8 6]
 [7 4 1 7 8]
 [6 5 4 2 8]
 [5 8 3 4 2]
 [1 8 7 4 1]]


In [20]:
arr1=arr1.reshape(1,25)
print(arr1)

[[5 2 6 8 6 7 4 1 7 8 6 5 4 2 8 5 8 3 4 2 1 8 7 4 1]]


In [21]:
arr1=arr1.reshape(5,5)
print(arr1)

[[5 2 6 8 6]
 [7 4 1 7 8]
 [6 5 4 2 8]
 [5 8 3 4 2]
 [1 8 7 4 1]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [ ]:
arr1=np.random.randint(1,11,size=(5,5))
print(arr1)

[[10  7  9  4 10]
 [ 5 10  1  3  6]
 [ 7  3  8  1  1]
 [10  9  7  5  8]
 [ 6  7  5  4  7]]


In [4]:
corners_indices = np.ix_((0, -1), (0, -1))
print(arr1[corners_indices])

[[10 10]
 [ 6  7]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [5]:
arr2=np.arange(16).reshape(4,4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [7]:
arr2[arr2>10]=10
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 10]
 [10 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [15]:
datatype=[('name','U10'),('age','i4'),('weight','f8')]
struct_array=np.array([('Pradyumn',25,97.8),('PB',22,79),('P Bisht',21,72.6),('Prady',19,105)],dtype=datatype)
print(struct_array)

[('Pradyumn', 25,  97.8) ('PB', 22,  79. ) ('P Bisht', 21,  72.6)
 ('Prady', 19, 105. )]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:
datatype=[('x','f8'),('y','f8')]
struct_array=np.array([(1,2),(6,9)],dtype=datatype)
print(struct_array)

(1.0, 2.0)


In [19]:
point1 = np.array(struct_array[0].tolist())
point2 = np.array(struct_array[-1].tolist())

print(np.linalg.norm(point2-point1))

8.602325267042627


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [25]:
data=np.random.randint(1,15,size=(4,4))
print(data)

[[ 9  8 14  1]
 [12 14  1  9]
 [ 5 13 11  5]
 [ 4 11  1  9]]


In [26]:
ma=np.ma
mx=ma.masked_array(data,mask=data>10)
print(mx)

[[9 8 -- 1]
 [-- -- 1 9]
 [5 -- -- 5]
 [4 -- 1 9]]


In [27]:
print("Sum",ma.sum(mx))

Sum 52


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [69]:
data=np.random.randint(1,15,size=(3,3))
print(data)

[[ 9 14  4]
 [ 5 12  4]
 [ 9  3  3]]


In [70]:
mask_diagonal=np.eye(3,dtype=bool)

In [71]:
mx=ma.masked_array(data,mask=mask_diagonal)
print(mx)
mean=int(ma.mean(mx))
print("Mean :",mean)

[[-- 14 4]
 [5 -- 4]
 [9 3 --]]
Mean : 6


In [72]:
mx = mx.filled(fill_value=mean)
print(mx)

[[ 6 14  4]
 [ 5  6  4]
 [ 9  3  6]]
