In [2]:
import pandas as pd
import numpy as np

### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.


In [18]:
data=np.arange(24).reshape(4,6)
print(data)
df=pd.DataFrame(data,index=data[:,0])
df

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


0   1   2   3   4   5
0    0   1   2   3   4   5
6    6   7   8   9  10  11
12  12  13  14  15  16  17
18  18  19  20  21  22  23

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'

In [20]:
columns=['A','B','C']
index=['X','Y','Z']
data=np.arange(9).reshape(3,3)
print(data)
df=pd.DataFrame(data,columns=columns,index=index)
df

[[0 1 2]
 [3 4 5]
 [6 7 8]]


A  B  C
X  0  1  2
Y  3  4  5
Z  6  7  8

In [29]:
print(df.loc['Y','B'])

4


### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [30]:
data=np.random.randint(1,16,size=(5,3))
print(data)

[[ 6 10  3]
 [10  3  7]
 [13 13  1]
 [ 1 13  3]
 [ 2  8 11]]


In [31]:
df=pd.DataFrame(data)
df

0   1   2
0   6  10   3
1  10   3   7
2  13  13   1
3   1  13   3
4   2   8  11

In [36]:
df['product']=df.iloc[:,0]*df.iloc[:,1]
df

0   1   2  product
0   6  10   3       60
1  10   3   7       30
2  13  13   1      169
3   1  13   3       13
4   2   8  11       16


2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [37]:
data=np.random.randint(1,13,size=(4,3))
print(data)

[[ 1  4  8]
 [11  4  1]
 [ 5 12  5]
 [ 3  5  7]]


In [38]:
df=pd.DataFrame(data)
df

0   1  2
0   1   4  8
1  11   4  1
2   5  12  5
3   3   5  7

In [39]:
row_sum=df.sum(axis=1)
print(row_sum)

0    13
1    16
2    22
3    15
dtype: int64


In [40]:
col_sum=df.sum(axis=0)
print(col_sum)

0    20
1    25
2    21
dtype: int64


### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.


In [63]:
data=np.random.randint(1,13,size=(5,3))
print(data)

[[ 2 12  4]
 [12  2  8]
 [11  9  1]
 [10  4  3]
 [ 7  2 11]]


In [64]:
df=pd.DataFrame(data)
df

0   1   2
0   2  12   4
1  12   2   8
2  11   9   1
3  10   4   3
4   7   2  11

In [65]:
df=df.mask(df>9,np.nan)
df

0    1    2
0  2.0  NaN  4.0
1  NaN  2.0  8.0
2  NaN  9.0  1.0
3  NaN  4.0  3.0
4  7.0  2.0  NaN

In [66]:
print(df.mean(axis=None))
df_filled=df.fillna(int(df.mean(axis=None)))
df_filled

4.2


0    1    2
0  2.0  4.0  4.0
1  4.0  2.0  8.0
2  4.0  9.0  1.0
3  4.0  4.0  3.0
4  7.0  2.0  4.0

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values

In [79]:
data=np.random.randint(1,15,size=(6,4))
print(data)

[[11  6  4 10]
 [ 3  1  3 13]
 [ 8 12  9 11]
 [14 12  9  6]
 [ 9  9  9  4]
 [ 4 11  9  3]]


In [80]:
df=pd.DataFrame(data)
df

0   1  2   3
0  11   6  4  10
1   3   1  3  13
2   8  12  9  11
3  14  12  9   6
4   9   9  9   4
5   4  11  9   3

In [81]:
df[df>10]=np.nan
df

0    1  2     3
0  NaN  6.0  4  10.0
1  3.0  1.0  3   NaN
2  8.0  NaN  9   NaN
3  NaN  NaN  9   6.0
4  9.0  9.0  9   4.0
5  4.0  NaN  9   3.0

In [82]:
df.dropna(how='any',inplace=True)
df

0    1  2    3
4  9.0  9.0  9  4.0

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [14]:
values=np.random.randint(1,10,size=3)
print(values)

[8 2 3]


In [15]:
categories=np.array(['A','B','C'])
print(categories)

['A' 'B' 'C']


In [16]:
data = np.array([[x,y] for x in categories for y in values])
print(data)


[['A' '8']
 ['A' '2']
 ['A' '3']
 ['B' '8']
 ['B' '2']
 ['B' '3']
 ['C' '8']
 ['C' '2']
 ['C' '3']]


In [17]:
column=['Category','Value']
df=pd.DataFrame(data,columns=column)
df

Category Value
0        A     8
1        A     2
2        A     3
3        B     8
4        B     2
5        B     3
6        C     8
7        C     2
8        C     3

In [18]:
sum = df.groupby('Category').sum()

In [19]:
print(sum)

         Value
Category      
A          823
B          823
C          823


2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category

In [20]:
columns=[ 'Product', 'Category', 'Sales']

In [22]:
product=np.array(['xyz','abc'])
category=np.array(['good','bad'])
sales=np.array([200,500,950])

In [34]:
data=[[x,y,int(z)] for x in product for y in category for z in sales]
data

[[np.str_('xyz'), np.str_('good'), 200],
 [np.str_('xyz'), np.str_('good'), 500],
 [np.str_('xyz'), np.str_('good'), 950],
 [np.str_('xyz'), np.str_('bad'), 200],
 [np.str_('xyz'), np.str_('bad'), 500],
 [np.str_('xyz'), np.str_('bad'), 950],
 [np.str_('abc'), np.str_('good'), 200],
 [np.str_('abc'), np.str_('good'), 500],
 [np.str_('abc'), np.str_('good'), 950],
 [np.str_('abc'), np.str_('bad'), 200],
 [np.str_('abc'), np.str_('bad'), 500],
 [np.str_('abc'), np.str_('bad'), 950]]

In [35]:
df=pd.DataFrame(data,columns=columns)
df

Product Category  Sales
0      xyz     good    200
1      xyz     good    500
2      xyz     good    950
3      xyz      bad    200
4      xyz      bad    500
5      xyz      bad    950
6      abc     good    200
7      abc     good    500
8      abc     good    950
9      abc      bad    200
10     abc      bad    500
11     abc      bad    950

In [38]:
group_cat=df.groupby(['Product', 'Category'])['Sales'].sum()
print(group_cat)

Product  Category
abc      bad         1650
         good        1650
xyz      bad         1650
         good        1650
Name: Sales, dtype: int64


### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.


In [ ]:
df1 = pd.DataFrame({
    'EmployeeID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'EmployeeID': [2, 3, 4],
    'Department': ['HR', 'IT', 'Finance']
})


In [40]:
print(df1.merge(df2, how='inner'))

   EmployeeID     Name Department
0           2      Bob         HR
1           3  Charlie         IT


2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [ ]:
df1 = pd.DataFrame({
    'EmployeeID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'EmployeeID': [2, 3, 4],
    'Department': ['HR', 'IT', 'Finance']
})

In [43]:
print(df1.merge(df2, how='outer'))

   EmployeeID     Name Department
0           1    Alice        NaN
1           2      Bob         HR
2           3  Charlie         IT
3           4      NaN    Finance


### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values. 

In [47]:
import datetime
import random

def random_datetime(start, end):
    """Generate a random datetime between two datetime objects."""
    delta = end - start
    random_seconds = random.randint(0, int(delta.total_seconds()))
    return start + datetime.timedelta(seconds=random_seconds)

start = datetime.datetime(2025, 6, 1)
end = datetime.datetime(2025, 9, 30)

In [51]:
df = pd.DataFrame({
    'datetime': [random_datetime(start, end) for _ in range(30)],
    'values': [random.randint(1,50) for _ in range(30)]
})
df

datetime  values
0  2025-06-11 02:58:34      35
1  2025-06-30 15:09:09       8
2  2025-06-29 00:48:20       5
3  2025-09-08 19:29:41      10
4  2025-07-09 13:20:24      20
5  2025-09-06 07:41:54       6
6  2025-08-08 17:13:02      39
7  2025-06-23 04:42:52       3
8  2025-09-05 21:16:18      34
9  2025-07-18 21:46:09      35
10 2025-07-25 23:20:57      19
11 2025-06-10 07:17:34      30
12 2025-09-02 02:00:08      38
13 2025-06-18 02:26:59      12
14 2025-08-25 03:22:03      28
15 2025-06-25 17:26:34       6
16 2025-07-26 01:24:45      29
17 2025-09-28 17:41:03      22
18 2025-09-01 22:22:16      41
19 2025-09-13 07:26:06      30
20 2025-09-06 10:29:36      24
21 2025-09-09 17:46:22      41
22 2025-07-22 23:17:55      30
23 2025-09-07 06:41:30      36
24 2025-06-17 04:50:45       2
25 2025-06-08 02:01:23      19
26 2025-08-08 14:43:42       4
27 2025-06-09 04:13:01      18
28 2025-08-08 22:07:00      42
29 2025-08-08 21:40:27      26

In [55]:
resample=df.copy()
resample['datetime']=resample['datetime'].dt.month
resample

datetime  values
0          6      35
1          6       8
2          6       5
3          9      10
4          7      20
5          9       6
6          8      39
7          6       3
8          9      34
9          7      35
10         7      19
11         6      30
12         9      38
13         6      12
14         8      28
15         6       6
16         7      29
17         9      22
18         9      41
19         9      30
20         9      24
21         9      41
22         7      30
23         9      36
24         6       2
25         6      19
26         8       4
27         6      18
28         8      42
29         8      26

In [56]:
resample=resample.groupby('datetime').sum()
print(resample)

          values
datetime        
6            138
7            133
8            139
9            282


2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers.

In [59]:
date_index = pd.date_range(start='2021-01-01', end='2021-12-31', freq='D')

df = pd.DataFrame({
    'values': np.random.randint(1, 101, size=len(date_index))
}, index=date_index)

df.head()


values
2021-01-01      76
2021-01-02      37
2021-01-03      82
2021-01-04      52
2021-01-05      74

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [10]:
arr=[
    ['a','b','a','b','c','c'],
    [1,1,2,2,2,1]
]
index=pd.MultiIndex.from_arrays(arr,names=['letters','numbers'])
df=pd.DataFrame(np.random.randn(6,2),index=index,columns=['First','Second'])
df

First    Second
letters numbers                    
a       1        0.430951 -1.933962
b       1       -1.566659  0.777046
a       2       -0.636791 -0.506451
b       2        1.747757  0.665385
c       2        0.581912  1.324704
        1       -2.076249  1.498165

In [13]:
df.loc['a',1]

First     0.430951
Second   -1.933962
Name: (a, 1), dtype: float64

2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [14]:
arr=[
    ['Soda','Soda','Potato Chips','Potato Chips','Icecream','Icecream'],
    ['Non-Caloric','Caloric','Wafers','Crinkle cut','Dairy','Non-Dairy']
]
index=pd.MultiIndex.from_arrays(arr,names=['Categories','Subcategories'])
df=pd.DataFrame(np.random.randn(6,2),index=index,columns=['I Quater','II Quater'])
df

I Quater  II Quater
Categories   Subcategories                     
Soda         Non-Caloric    1.450604  -0.731811
             Caloric       -1.248218   0.488819
Potato Chips Wafers         0.623422  -0.508986
             Crinkle cut    0.171095  -0.872074
Icecream     Dairy         -1.167529   1.244627
             Non-Dairy     -0.806838  -1.069882

In [20]:
category_sum = df.groupby(level='Categories').sum()
category_sum


I Quater  II Quater
Categories                       
Icecream     -1.974368   0.174745
Potato Chips  0.794517  -1.381060
Soda          0.202386  -0.242992

In [21]:
subcategory_sum = df.groupby(level='Subcategories').sum()
subcategory_sum


I Quater  II Quater
Subcategories                     
Caloric       -1.248218   0.488819
Crinkle cut    0.171095  -0.872074
Dairy         -1.167529   1.244627
Non-Caloric    1.450604  -0.731811
Non-Dairy     -0.806838  -1.069882
Wafers         0.623422  -0.508986

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.


In [39]:
data = {
    'Date':['2025-08-12','2025-08-12','2025-03-22','2025-05-17','2025-08-07','2025-04-29'],
    'Category':['Sodas','Chips','Icecream','Chips','Icecream','Sodas'],
    'Value': [200,150,300,250,400,350]
    
}

df = pd.DataFrame(data)
df

Date  Category  Value
0  2025-08-12     Sodas    200
1  2025-08-12     Chips    150
2  2025-03-22  Icecream    300
3  2025-05-17     Chips    250
4  2025-08-07  Icecream    400
5  2025-04-29     Sodas    350

In [40]:
pivot=df.pivot_table(
    index='Date',
    columns='Category',
    values='Value',
    aggfunc='sum',
    fill_value=0
)
pivot

Category    Chips  Icecream  Sodas
Date                              
2025-03-22      0       300      0
2025-04-29      0         0    350
2025-05-17    250         0      0
2025-08-07      0       400      0
2025-08-12    150         0    200

2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'

In [50]:
data = {
   'Year':[2017,2017,2017,2017,2018,2018,2018,2018],
   'Quater':['I','II','III','I','I','II','III','I'],
   'Revenue':[5000,2000,7500,4500,3300,2310,7900,86000]

}

df = pd.DataFrame(data)
df

Year Quater  Revenue
0  2017      I     5000
1  2017     II     2000
2  2017    III     7500
3  2017      I     4500
4  2018      I     3300
5  2018     II     2310
6  2018    III     7900
7  2018      I    86000

In [51]:
pivot=df.pivot_table(
    index='Year',
    columns='Quater',
    values='Revenue',
    aggfunc='mean',
    fill_value=0
)
pivot

Quater        I      II     III
Year                           
2017     4750.0  2000.0  7500.0
2018    44650.0  2310.0  7900.0

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [93]:
import random
df=pd.DataFrame({
    'First':[random.randint(1,10) for _ in range(5)],
    'Second':[random.randint(1,10) for _ in range(5)],
    'Third':[random.randint(1,10) for _ in range(5)]
})
df

First  Second  Third
0      9       1      5
1      3       2      8
2      7       3      9
3     10       4      5
4      9       5      9

In [94]:
df=pd.DataFrame.map(df,lambda x:x*2)
df


First  Second  Third
0     18       2     10
1      6       4     16
2     14       6     18
3     20       8     10
4     18      10     18

2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [95]:
import random
df=pd.DataFrame({
    'First':[random.randint(1,10) for _ in range(6)],
    'Second':[random.randint(1,10) for _ in range(6)],
    'Third':[random.randint(1,10) for _ in range(6)]
})
df['Sum'] = df.apply(lambda row: row['First'] + row['Second'] + row['Third'], axis=1)
df

First  Second  Third  Sum
0      1       7      6   14
1      8       7      3   18
2      8       5      6   19
3      6       8      3   17
4      2       9      2   13
5      7      10      6   23

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.


In [69]:
import string
def random_string(length=6):
    letters = string.ascii_letters  # a–z, A–Z
    return ''.join(random.choice(letters) for _ in range(length))

In [76]:
series1 = pd.Series([random_string() for _ in range(5)])
series1

0    GuMIZH
1    nsirhe
2    TJIxYS
3    sjhRpC
4    DAjClr
dtype: object

In [77]:
series1=series1.apply(str.upper)
series1

0    GUMIZH
1    NSIRHE
2    TJIXYS
3    SJHRPC
4    DAJCLR
dtype: object

2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [96]:
series2 = pd.Series([random_string(10) for _ in range(5)])
series2

0    eEMLNgUEIH
1    AAnbBeCVTU
2    NtdvaFXTaV
3    ziLmlvLUGT
4    VjnMtOqoUv
dtype: object

In [97]:
new_series=pd.Series(series2.apply(lambda x: x[0:3]))
new_series

0    eEM
1    AAn
2    Ntd
3    ziL
4    Vjn
dtype: object